source 'https://rubygems.org'
ruby '2.1.5'

gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'jquery-ui-rails'
gem 'autoprefixer-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'haml-rails'
gem 'jquery-rails'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'animate-rails'
gem 'normalize-rails'
gem 'font_assets', github: 'ericallam/font_assets'
gem 'json'
gem 'rubyzoho'
gem 'actionpack-action_caching'
gem 'sitemap_generator'
gem 'intercom-rails'
gem 'airbrake'
gem 'newrelic_rpm'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'delayed_job_web'
gem 'geocoder'
gem 'rack-reverse-proxy', :require => 'rack/reverse_proxy'
gem 'nprogress-rails'
gem 'vacuum'
gem 'simple_form'
gem 'friendly_id'
gem 'devise'
gem 'gravatar_image_tag'
gem 'heap'
gem 'will_paginate'
gem 'derailed'
gem 'textacular'
gem 'mailchimp-api', require: 'mailchimp'
gem 'vex_rails'

gem 'unicorn'

group :development, :test do
  gem 'html2haml'
  gem 'database_cleaner'
  gem 'simplecov'
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'rack-mini-profiler'
  gem 'rspec-rails'
  gem 'rspec-activejob'
  gem 'teaspoon-jasmine'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'erb2haml'
end

group :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'rack_session_access'
  gem 'webmock'
end

group :production do
  gem 'rails_12factor'
  gem 'workless'
end
